#!/bin/bash

echo "=== INIZIO PIPELINE DI TEST PERFORMANCE ==="

# RUST
echo "--> Avvio Test Rust..."
cd rust
cargo run --release
echo "Rust completato. RAM liberata."


# JULIA
echo "--> Avvio Test Julia..."
julia choleski_method.jl
echo "Julia completato. RAM liberata."
sleep 5

# MATLAB
echo "--> Avvio Test Matlab..."
matlab -batch choleski_method.m
echo "Matlab completato. RAM liberata."
sleep 5


echo "=== TUTTI I TEST SONO STATI COMPLETATI! ==="